baseurl = "https://rafed.github.io/"
languageCode = "en-us"
title = "Rafed Muhammad Yasir"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Rafed Muhammad Yasir"
	description = "Software Engineer"
	copyright = "Released under the MIT license"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/rafed"

	#version = "1.0.0"
	logo = "image/rafed.jpg"
	favicon = "image/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "rafed"
	email   = "rafed123@gmail.com"


[[menu.main]]
	name   = "About me"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Academics & Publications"
	url    = "academics/"
	weight = 2

[[menu.main]]
	name   = "Development Skills"
	url    = "skills/"
	weight = 3

[[menu.main]]
	name   = "Software Projects"
	url    = "projects/"
	weight = 4

[[menu.main]]
	name   = "Experience & Achievements"
	url    = "experience/"
	weight = 5

[[menu.main]]
	name   = "Others"
	url    = "others/"
	weight = 6


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
	hrefTargetBlank = true
