name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # personal_token: ${{ secrets.TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # external_repository: rafed/devra
          publish_dir: ./public
          #   keep_files: true
          user_name: rafed
          user_email: rafed123@gmail.com
          publish_branch: master
        #   cname: example.com
